SELECT 
    _FIVETRAN_ID,
    ADD_TO_CART_QUANTITY,
    REMOVE_FROM_CART_QUANTITY,
    SESSION_ID,
    ITEM_VIEW_AT AS ITEM_VIEW_AT_TS,
    ITEM_NAME,
    PRICE_PER_UNIT,
    _FIVETRAN_DELETED,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM {{source('snowflake', 'ITEM_VIEWS')}}