WITH ranking AS(
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY SESSION_ID ORDER BY ITEM_VIEW_AT DESC) as row_n
    FROM {{source('snowflake', 'ITEM_VIEWS')}}
)
SELECT 
    _FIVETRAN_ID,
    ADD_TO_CART_QUANTITY,
    REMOVE_FROM_CART_QUANTITY,
    SESSION_ID,
    ITEM_VIEW_AT AS ITEM_VIEW_AT_TS,
    ITEM_NAME,
    PRICE_PER_UNIT,
    _FIVETRAN_DELETED,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM ranking
WHERE row_n = 1