WITH ranking AS(
    SELECT *,
        ROW_NUMBER() OVER (PARTITION BY SESSION_ID ORDER BY SESSION_AT DESC) as row_n
    FROM {{source('snowflake', 'SESSIONS')}}
)
SELECT  
    CLIENT_ID,
    IP,
    OS,
    SESSION_AT AS SESSION_AT_TS,    
    SESSION_ID,
    _FIVETRAN_DELETED,
    _FIVETRAN_ID,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS
FROM ranking
WHERE row_n = 1