SELECT 
    _FILE,
    _LINE,
    _MODIFIED AS _MODIFIED_TS,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,
    DATE AS EXPENSE_RECORD_DATE,
    EXPENSE_TYPE,
    CASE WHEN EXPENSE_AMOUNT LIKE '$%' THEN CAST(SUBSTRING(EXPENSE_AMOUNT, 2) AS DECIMAL)
    ELSE EXPENSE_AMOUNT END AS EXPENSE_AMOUNT
FROM {{source('google_drive', 'EXPENSES')}} 