SELECT
    _FILE,
    _LINE,
    _MODIFIED,
    _FIVETRAN_SYNCED,
    CAST(EMPLOYEE_ID AS STRING) as EMPLOYEE_ID,
    CAST(SUBSTRING(QUIT_DATE,4) AS DATE) as QUIT_DATE,
FROM {{source('google_drive', 'HR_QUITS')}}