SELECT
    _FILE,
    _LINE,
    _MODIFIED AS _MODIFIED_TS,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,
    CAST(EMPLOYEE_ID AS STRING) as EMPLOYEE_ID,
    CAST(QUIT_DATE AS DATE) as QUIT_DATE,
FROM {{source('google_drive', 'HR_QUITS')}}