SELECT  
    _FILE,
    _LINE,
    _MODIFIED AS _MODIFIED_TS,
    _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,
    CAST (EMPLOYEE_ID AS STRING) AS EMPLOYEE_ID,
    CAST(SUBSTRING(HIRE_DATE,4) AS DATE) AS HIRE_DATE,
    NAME AS EMPLOYEE_NAME_ALIAS,
    CITY,
    ADDRESS AS ADDRESS_ALIAS,
    TITLE,
    ANNUAL_SALARY
FROM {{source('google_drive', 'HR_JOINS')}} 